### ISSUE TITLE
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by zanshuxun** [Sweetnow/group-buying-recommendation#1]
作者您好，我安装了requirements.txt和librecframework之后运行GBGCN.py，遇到了以下错误：
Traceback (most recent call last):
  File "GBGCN.py", line 14, in <module>
    from librecframework.argument.manager import HyperparamManager
  File "C:\Users\ZSX\AppData\Roaming\Python\Python36\site-packages\librecframework\argument\__init__.py", line 11, in <module>
    class Argument(NamedTuple, Generic[T]):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

请问这是什么情况呢

**Comment by Sweetnow** [comment]
librecframework需要Python版本在3.8或以上

**Comment by zanshuxun** [comment]
感激不尽！
