### ISSUE TITLE
Negative sample files

### ISSUE THREAD

**Issue by Ali-khn** [Sweetnow/group-buying-recommendation#3]
Hi, 
My question is how to use negative sample file in order to run the whole model correctly? should I copy the file in BeiBei folder? Can I run the model correctly without "negative sample file"? Any instruction from scratch would be of any help.
Thanks

**Comment by Sweetnow** [comment]
To use negative sample file, just download it, unzip it and copy *.negative.txt into BeiBei folder.

It is OK to run the model without genative sample file, but the framwork will do sampling before training and save it, which spends a lot of time.

**Comment by Ali-khn** [comment]
Thanks for your response.
