### ISSUE TITLE
您好，我在复现您的代码时遇到以下问题，想请教一下。

### ISSUE THREAD

**Issue by Ganoder** [Sweetnow/group-buying-recommendation#4]
命令： python GBGCN.py train [-h]
错误：
Using backend: pytorch
usage: GBGCN.py train [-h] [-DS DATASET] [-D DEVICE [DEVICE ...]] -T TAG [-SEP SAMPLE_EPOCH] [-SW SAMPLE_WORKER] [-EP EPOCH]
                      [-BS BATCH_SIZE] [-BW BATCH_WORKER] [-TBS TEST_BATCH_SIZE] [-TBW TEST_BATCH_WORKER] [-EB EMBEDDING_SIZE]
                      [--lr LR [LR ...]] --L2 L2 [L2 ...] --SL2 SL2 [SL2 ...] -L LAYER [LAYER ...] -A ALPHA [ALPHA ...] -B
                      BETA [BETA ...] [--act ACT] [--pretrain | --no-pretrain]
GBGCN.py train: error: the following arguments are required: -T/--tag, --L2, --SL2, -L/--layer, -A/--alpha, -B/--beta

**Comment by Sweetnow** [comment]
代码的运行需要输入一定的命令行参数，该报错给出的原因是输入当中缺少必须的输入。

另外，在命令行系统的使用方法（usage）中，一般而言用[]包括的内容是可选项，不用[]包括的内容是必选项。

在本代码中，必须要输入的有：
- `-T`：训练/测试的标签
- `--L2`：训练时正则项系数
- `--SL2`：有关社交部分的正则项系数
- `-L`：视图内内传播的GCN层数
- `-A`：论文中`\alpha`系数的值
- `-B`：论文中`\beta`系数的值

也可以使用`python GBGCN.py train -h`来获得详细地说明，其中`-h`参数不需要被方括号包含。

**Comment by Ganoder** [comment]
谢谢您的回复！祝您生活愉快。
