### ISSUE TITLE
About training GBGCN with a pretrained GBMF model

### ISSUE THREAD

**Issue by vincenttsai2015** [Sweetnow/group-buying-recommendation#6]
Hi,

When trying to train GBGCN with a pretrained GBMF model, the following error occurs......

![image](https://user-images.githubusercontent.com/13366052/146413728-4a8334a5-3b88-4891-9386-c5398a95cd0f.png)

I'm wondering how to solve such errors. Thanks.

**Comment by Sweetnow** [comment]
the pretrain model json file contains the path to the `pretrain model` file (maybe *.pth) rather than `model.json`.

**Comment by vincenttsai2015** [comment]
Got it. I am able to use the pretrained model by modifying pretrain.json. Thanks.
