### ISSUE TITLE
About ranking metric evaluation

### ISSUE THREAD

**Issue by vincenttsai2015** [Sweetnow/group-buying-recommendation#8]
Hi,

I'm wondering if it is possible to evaluate the ranking metrics of MAP(mean average precision) @ K and HR(hit ratio) @ K of GBMF/GBGCN under librecframework. If yes, how can I modify the code? Thanks.

**Comment by Sweetnow** [comment]
You can modify the framework https://github.com/Sweetnow/librecframework/blob/master/librecframework/metric.py.

Just follow the current code,
- create a new class derived from `Metric`
- implement `__call__` (score is the model output, ground_truth is the corresponding data from `Dataset.__getitem__`
- plus the metric into `self._sum`
- plus the count into `self._cnt`
- register the metric class into _ALL_METRICS

And then, you can choose the new metric in config.json by its class name.

**Comment by Sweetnow** [comment]
BTW, I think HR is the same as Precision.
