### ISSUE TITLE
It was killed before the training process started when the code was reproduced

### ISSUE THREAD

**Issue by ZQSong1997** [Sweetnow/group-buying-recommendation#9]
hello，I want to know what the computer configuration should be to successfully reproduce these jobs. I can't reproduce it on 2080ti with 11gb of memory, and it's useless when I try to make the batchsize small enough. Or can you specify the hyperparameter setting?

**Comment by Sweetnow** [comment]
Can you provide more information like logs about your problem? Your GPU memory is enough for the program.

**Comment by ZQSong1997** [comment]
当我按照步骤配好环境后，执行以下命令（python3 GBECM.py train --dataset BeiBei -T TAG -BS 4096 -BW 8 --lr 0.01 --L2 0.01 --SL2 0.01 -L 2 -A 0.6 -8 0.05）以训练模型，出现了如下错误：OverflowError: cannot serialize a bytes object larger than 4 GiB.

于是我尝试调小-BS或令-BW为0，同样会出错，后面我根据网上教程（[https://www.pythonf.cn/read/108500）中的方式3解决了这一问题。但程序执行一会就会出现"已杀死”提示，自此程序结束运行。如下：

![image](https://user-images.githubusercontent.com/46641090/158181489-34c98c8f-042f-49a7-a5ff-0da81e590b94.png)

请问这是什么原因呢？

**Comment by Sweetnow** [comment]
请问你的机器内存多大，以及能否在程序运行过程中观察一下程序所占用的内存的变化。

目前看来怀疑是内存占满后程序被操作系统杀死。

如果确实是该原因导致，可以设置`-SEP 200`将`sample-epoch`改为一个较小的数值，或设置`-SW 4`将`sample-worker`减小，或在一台内存较大的机器上完成预采样后将采样文件（将出现在数据集目录中）复制到GPU机器上。

*程序会在启动后进行负样本的预采样，默认是产生可供500epoch训练的正负样本对，这个过程会消耗大量CPU算力与内存。*

**Comment by ZQSong1997** [comment]
我的机器内存是64GB,GPU的有11GB,我将-SEP降低为50，-SW降为2才不会被杀死，可截止目前过去了七八个小时命令行也没有动静，没出现新的提示，现在我已经主动停掉了。

**Comment by Sweetnow** [comment]
如果是linux系统，建议用`htop`观察一下预采样过程中内存与CPU占用的变化情况，预采样过程命令行是不会有任何提示的，且所需要的时间较长。

建议在观察内存与CPU占用的基础上，提高sample worker的数量以加快采样过程。

对于机器内存，我们预采样使用的机器是256GB内存（128GB物理内存+128GB虚拟内存），建议可以增加一下系统的虚拟内存。

**Comment by Sweetnow** [comment]
如果后续依然有该问题，请Reopen本Issue
